### PR TITLE
Throwing error for an 'invalid main entry'

### LINKED ISSUE #143: loadNodeModules() should be more clear about what went wrong
I had an error loading a library, but all it told me is that it couldn't resolve the module. That's fine, but the real issue is that the package's main file didn't exist.

Here's some payload information:

``` js
{ x: 'snabbdom-view',
  start: '/Users/krainboltgreene/Code/krainboltgreene/deushack/source/client/cycle',
  dirs: [] }
```

We can definitely make this better. We can say all the directories we looked in, what exact file we;'re looking for (in this case main) and then do some reading to show the user that it's the package;'s fault.

### LINKED ISSUE #223: Error messages are not precise enough
I tried to run `resolve` against a library which had an invalid `main` field in `package.json`.

With `require.resolve()`, the error message is:

```
> require.resolve('mylib')
Uncaught:
Error: Cannot find module '/home/me/code/cv-website/node_modules/mylib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/me/code/cv-website/node_modules/mylib/package.json',
  requestPath: 'mylib'
}
```

With `resolve`, it is:

```
> resolve.sync('mylib')
Uncaught Error: Cannot find module 'mylib' from '.'
    at Function.resolveSync [as sync] (/home/me/code/cv-website/node_modules/resolve/lib/sync.js:89:15) {
  code: 'MODULE_NOT_FOUND'
}
```

Missing error information was critical in my use case, and it took some time to figure out why `resolve` was failing.

### PR DESCRIPTION
**Pull request by Cheesetouched**
Fixes #223 & Possibly Fixes #143 too.

Fix

The thrown error now suggests the possibility of an invalid main entry in the _package.json_.

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Thanks! This will need some regression tests - and I'd want to be convinced (ideally, via tests) that the swallowed errors are only coming from `path.resolve(x, pkg.main)` and not from `loadAsDirectorySync`, etc.

**Comment by ljharb** [comment]
You can also see that tests are currently failing - https://github.com/browserify/resolve/pull/234/checks?check_run_id=1471328733 - which implies that the *intentional* behavior with an incorrect "main" is to silently fall back to `index.js`, *when present*.

Specifically, when I put [this directory](https://github.com/browserify/resolve/tree/master/test/resolver/incorrect_main) inside a `node_modules` folder, and hop into the node repl and do `require.resolve('incorrect_main')`, i get `$PWD/node_modules/incorrect_main/index.js`, not an error. When I remove `$PWD/node_modules/incorrect_main/index.js`, however, I get `Error: Cannot find module '$PWD/node_modules/incorrect_main/wrong.js'. Please verify that the package.json has a valid "main" entry`.

So, I think you specifically have to only error in the case where an *explicit* main *and* an implicit main are not found.

**Comment by Cheesetouched** [comment]
Yep, makes sense to me. I'll focus on isolating explicit and implicit main conditions first. Will fallback here if something doesn't add up.

**Comment by Cheesetouched** [comment]
@ljharb There. That should do the trick. Thoughts?

P.S Not sure why that 1 test is failing. Could you please explain?

File: lib/sync.js [hunk 1]
```diff
@@ -167,12 +167,19 @@ module.exports = function resolveSync(x, options) {
...
+                if (n) return n;
+                else {
+                    var checkIndex = loadAsFileSync(path.resolve(x, 'index.js'));
+                    if (checkIndex) return checkIndex;
+                    else {
+                        var incorrectMainError = new Error("Cannot find module '" + path.resolve(x, pkg.main) + "'. Please verify that the package.json has a valid \"main\" entry");
+                        incorrectMainError.code = 'INCORRECT_PACKAGE_MAIN';
+                        throw incorrectMainError;
+                    }
+                }
```
Comment (ljharb) [inline lib/sync.js:182]:
```suggestion
                try {
                  var mainPath = path.resolve(x, pkg.main);
                  var m = loadAsFileSync(mainPath);
                  if (m) return m;
                  var n = loadAsDirectorySync(mainPath);
                  if (n) return n;
                  var checkIndex = loadAsFileSync(path.resolve(x, 'index.js'));
                  if (checkIndex) return checkIndex;
                } catch (e) {}
                var incorrectMainError = new Error("Cannot find module '" + path.resolve(x, pkg.main) + "'. Please verify that the package.json has a valid \"main\" entry");
                incorrectMainError.code = 'INCORRECT_PACKAGE_MAIN';
                throw incorrectMainError;
```

**Review by ljharb — COMMENTED** [review]
We'll need an async fix also.

**Comment by Cheesetouched** [comment]
@ljharb  Implemented the changes for async.js as well. Can you do a quick review?

**Comment by ljharb** [comment]
@Cheesetouched seems good, but tests would really be persuasive :-)

**Comment by Cheesetouched** [comment]
Absolutely. I am on it.

**Comment by Cheesetouched** [comment]
@ljharb See if this looks good to you? Feel free to suggest more changes.

File: test/resolver.js [hunk 2]
```diff
@@ -284,6 +284,14 @@ test('incorrect main', function (t) {
     });
 });
 
+test('missing main', function (t) {
+    var resolverDir = path.join(__dirname, 'resolver');
+    resolve('./missing_main', { basedir: resolverDir }, function (err, res, pkg) {
+        if (!err) t.fail('No error thrown when main was found missing.');
+        t.end();
```
Comment (Cheesetouched) [inline test/resolver.js:291]: Another way of doing this would be:
```
if (err && err.code === 'INCORRECT_PACKAGE_MAIN') t.pass('Done');
t.end();
```

Which one would you prefer, @ljharb?

Comment (ljharb) [reply test/resolver.js:291]: I like tests that check more things - how about:
```js
        t.error(err, 'an error was thrown with a missing main');
        t.equal(err && err.code, 'INCORRECT_PACKAGE_MAIN', 'error has correct error code');
        t.end();
```

File: test/resolver/missing_main/package.json [hunk 3]
```diff
@@ -0,0 +1,3 @@
+{
+  "main": "index.js"
+}
```
Comment (ljharb) [inline test/resolver/missing_main/package.json:3]: it might be nice to add *another* fixture for when "main" points to "not index.js", and that main is missing, and "index.js" is also missing :-)

Comment (Cheesetouched) [reply test/resolver/missing_main/package.json:3]: Yep. On this.

File: test/resolver.js (hunk 2 above)
Comment (Cheesetouched) [reply test/resolver.js:291]: `t.error(err, 'an error was thrown with a missing main');`

This line is causing the test to fail, probably because `t.error(obj, message, extra)` fails the assertion if `obj` is an error, according to the [docs](https://node-tap.org/docs/api/asserts/#terrorobj-message-extra).

Comment (ljharb) [reply test/resolver.js:291]: oh oops, in that case `t.ok(err instanceof Error` or something?

File: test/resolver/missing_main/package.json (hunk 3 above)
Comment (Cheesetouched) [reply test/resolver/missing_main/package.json]: @ljharb Added relevant test cases. Ready for review.

**Comment by Cheesetouched** [comment]
@ljharb Added relevant test cases. Ready for review.

**Review by ljharb — APPROVED** [review]
Seems good! I'm still hesitant to backport this to v1, and will think about it more, but at least we can land this in the next v2 prerelease :-)

**Comment by ljharb** [comment]
whoops, merged a little early, but i think we're ok :-)

**Comment by Cheesetouched** [comment]
@ljharb Any issues? Happy to take to care of it. Do let me know.

**Comment by ljharb** [comment]
nah, i just meant to wait til all the status checks had finished, and i pulled the trigger a bit prematurely. everything still passed tho.
